# Generated by Django 4.1.2 on 2022-12-02 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sessao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempo_inicio', models.TimeField(blank=True, verbose_name='Início da sessão')),
                ('tempo_fim', models.TimeField(null=True, verbose_name='Fim da sessão')),
            ],
        ),
    ]
