# Generated by Django 4.1.3 on 2022-12-01 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sessao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempo_inicio', models.TimeField(blank=True, verbose_name='Início da sessão')),
                ('tempo_fim', models.TimeField(blank=True, verbose_name='Fim da sessão')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.aluno')),
            ],
        ),
    ]
