# Generated by Django 4.1.3 on 2022-11-28 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField(blank=True, verbose_name='Dia da aula')),
                ('hora', models.TimeField(blank=True, verbose_name='Horário da aula')),
                ('duracao', models.TimeField(blank=True, default=0, verbose_name='Duração da aula')),
                ('vagas', models.IntegerField(blank=True, default=0, verbose_name='Número de vagas')),
                ('visivel', models.BooleanField(blank=True, verbose_name='Visível')),
                ('inscritos', models.IntegerField(blank=True, default=0, verbose_name='Número de inscritos')),
            ],
        ),
        migrations.CreateModel(
            name='Exercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=255, verbose_name='Nome do exercício')),
                ('urlfoto', models.CharField(blank=True, max_length=255, verbose_name='URL da imagem do exercicio')),
                ('maquina', models.CharField(blank=True, max_length=255, verbose_name='Nome da máquina')),
            ],
        ),
        migrations.CreateModel(
            name='Modalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=255, verbose_name='Nome da modalidade')),
                ('descrição', models.TextField(blank=True, verbose_name='Descrição da modalidade')),
            ],
        ),
        migrations.CreateModel(
            name='Treino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.IntegerField(blank=True, verbose_name='Nível de dificuldade')),
                ('comentario', models.TextField(blank=True, verbose_name='Comentários')),
                ('criado', models.BooleanField(blank=True, default=False, verbose_name='Já foi montado?')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.aluno')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.professor')),
            ],
        ),
        migrations.CreateModel(
            name='Itemtreino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carga', models.IntegerField(blank=True, verbose_name='Carga do exercício')),
                ('repeticao', models.IntegerField(blank=True, verbose_name='Número de repetições')),
                ('exercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professores.exercicio')),
                ('treino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professores.treino')),
            ],
        ),
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alunos', models.ManyToManyField(blank=True, to='user.aluno')),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professores.aula')),
            ],
        ),
        migrations.AddField(
            model_name='aula',
            name='modalidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professores.modalidade'),
        ),
        migrations.AddField(
            model_name='aula',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.professor'),
        ),
    ]
