# Generated by Django 4.1.3 on 2022-11-15 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_aluno_email_professor_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(blank=True, verbose_name='Dia e hora da aula')),
                ('visível', models.BooleanField(blank=True, verbose_name='Visível')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.professor')),
            ],
        ),
        migrations.CreateModel(
            name='Exercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=255, verbose_name='Nome do exercício')),
                ('urlfoto', models.CharField(blank=True, max_length=255, verbose_name='URL da imagem do exercicio')),
            ],
        ),
        migrations.CreateModel(
            name='Itemtreino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carga', models.IntegerField(blank=True, verbose_name='Carga do exercício')),
                ('exercicios', models.ManyToManyField(blank=True, to='professores.exercicio')),
            ],
        ),
        migrations.CreateModel(
            name='Treinos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.IntegerField(blank=True, verbose_name='Nível de dificuldade')),
                ('comentario', models.TextField(blank=True, verbose_name='Comentários')),
                ('Itens_treino', models.ManyToManyField(blank=True, to='professores.itemtreino')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.aluno')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.professor')),
            ],
        ),
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alunos', models.ManyToManyField(blank=True, to='user.aluno')),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professores.aula')),
            ],
        ),
    ]
