# Generated by Django 4.1.3 on 2022-11-15 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='treinos',
            name='Criado',
            field=models.BooleanField(blank=True, default=False, verbose_name='Já foi montado?'),
        ),
    ]
