# Generated by Django 4.1.3 on 2022-11-15 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('professores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='treinos',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.aluno'),
        ),
        migrations.AddField(
            model_name='treinos',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.professor'),
        ),
        migrations.AddField(
            model_name='itemtreino',
            name='exercicios',
            field=models.ManyToManyField(blank=True, to='professores.exercicio'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='alunos',
            field=models.ManyToManyField(blank=True, to='user.aluno'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='aula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professores.aula'),
        ),
        migrations.AddField(
            model_name='aula',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.professor'),
        ),
    ]
