# Generated by Django 4.1.3 on 2022-11-28 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professores', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modalidade',
            old_name='descrição',
            new_name='descricao',
        ),
    ]
