# Generated by Django 4.1.3 on 2022-11-14 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='Endereco',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='altura',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='bracos',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='cinturaescapular',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='coxa',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='email',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='idade',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='peitoral',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='percentualgordura',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='peso',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='telefone',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='urlfoto',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='Endereco',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='cref',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='idade',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='telefone',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='urlfoto',
        ),
    ]
