# Generated by Django 4.1.3 on 2022-11-15 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='secretario',
        ),
    ]
